### ISSUE TITLE
need to update tty_acs_table_putty[]

### ISSUE THREAD

**Issue by koie-hidetaka** [z80oolong/tmux-eaw-fix#1]
`tty_acs_table_putty` must have same key as `tty_acs_table` since `nitems(tty_acs_table)` but missing b,c,d,e.
Or switch nitems() in tty_acs_get().

https://github.com/tmux/tmux/commit/9b83b1daa6caee4d2c665c26da37866712c555a8

**Comment by z80oolong** [comment]
Thanks to [Mr. Koie-Hidetaka][1] for pointing out the tmux difference file in the issue.
The missing part of the array ```tty_acs_table_putty[]``` and the function ```tty_acs_get()``` have been corrected and the tmux difference file has been updated.
Please check the difference file.

[1]:https://github.com/koie-hidetaka
